import Head from 'next/head'
import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>The Simpsons</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/The-Simpsons-icon.png" />
        <link
            rel="preload"
            href="/fonts/akbar.ttf"
            as="font"
            type="font/ttf"
            crossOrigin="anonymous"
          />
          <link
            rel="preload"
            href="/fonts/simpsonfont-webfont.woff"
            as="font"
            type="font/woff"
            crossOrigin="anonymous"
          />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          The Simpsons
        </h1>
      </main>
    </div>
  )
}
