import Head from 'next/head'
import SectionCard from '../components/sections'
import styles from '../styles/Home.module.scss'

export const sections = [
  { "id": "1", "name": "Episodes","link": "episodes", "image": "https://res.cloudinary.com/dp7vfoqbw/image/upload/v1670793347/simpsons_xbg6jd.jpg" },
  { "id": "2", "name": "Locations","link": "locations", "image": "https://res.cloudinary.com/dp7vfoqbw/image/upload/v1670793347/simpsons_xbg6jd.jpg" },
  { "id": "3", "name": "Characters","link": "characters", "image": "https://res.cloudinary.com/dp7vfoqbw/image/upload/v1670793347/simpsons_xbg6jd.jpg" }
]

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>The Simpsons</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/The-Simpsons-icon.png" />
        <link
          rel="preload"
          href="/fonts/akbar.ttf"
          as="font"
          type="font/ttf"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href="/fonts/simpsonfont-webfont.woff"
          as="font"
          type="font/woff"
          crossOrigin="anonymous"
        />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          The Simpsons
        </h1>
        <div className={styles.sections}>
          {sections.map((section: any) => (
            <SectionCard key={section.id} sectionItem={section} />
          ))}
        </div>
      </main>
    </div>
  )
}
